CREATE TABLE INDI_CUSTOMER(
	CUS_ID VARCHAR(10) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	GENDER VARCHAR(6) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	PRIMARY KEY(CUS_ID)
); 

CREATE TABLE ORG_CUSTOMER(
	CUS_ID VARCHAR(10) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	PRIMARY KEY(CUS_ID)
); 

CREATE TABLE BRANCH(
	BRANCH_ID VARCHAR(10) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	PRIMARY KEY(BRANCH_ID)
); 

CREATE TABLE FD_PLAN(
	FD_PLAN_ID VARCHAR(10) NOT NULL,
	INTEREST_RATE FLOAT(5,3) NOT NULL,
	TIME_PERIOD INT(3) NOT NULL,
	PRIMARY KEY(FD_PLAN_ID)
); 

CREATE TABLE LOAN_TYPE(
	TYPE_ID VARCHAR(10) NOT NULL,
	INTEREST_RATE FLOAT(5,3) NOT NULL,
	PERIOD INT(3) NOT NULL,
	PRIMARY KEY(TYPE_ID)
); 
CREATE TABLE SAVING_ACCOUNT_TYPE(
	TYPE_ID VARCHAR(10) NOT NULL,
	INTEREST_RATE FLOAT(5,3) NOT NULL,
	MIN_BALANCE FLOAT(5,2) NOT NULL,
	PRIMARY KEY(TYPE_ID)
);

CREATE TABLE MANAGER(
	MANAGER_ID VARCHAR(10) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONTACT_NUMBER CHAR(10),
	EMAIL_ADDRESS VARCHAR(30),
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(16) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	SALARY FLOAT(8,3) NOT NULL,
	BRANCH_ID VARCHAR(10) NOT NULL, 
	PRIMARY KEY(MANAGER_ID),
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
 	ON DELETE CASCADE 
); 

CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID VARCHAR(10) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	CONTACT_NUMBER CHAR(10),
	EMAIL_ADDRESS VARCHAR(30),
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(16) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	SALARY FLOAT(8,3) NOT NULL,
	BRANCH_ID VARCHAR(10) NOT NULL, 
	PRIMARY KEY(EMPLOYEE_ID),
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) 
	ON DELETE CASCADE
);

CREATE TABLE SAVING_ACCOUNT(
	ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
	BALANCE NUMERIC(15,3) CHECK (BALANCE>1000),
	BRANCH_ID VARCHAR(10) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(16) NOT NULL,
	EMAIL_ADDRESS VARCHAR(20) NOT NULL,
	WITHDRAWAL_COUNT_PER_MONTH INT(3) CHECK (WITHDRAWAL_COUNT_PER_MONTH<6),
	CONTACT_NUMBER VARCHAR(10),
	CUS_ID VARCHAR(10) NOT NULL,
	TYPE_ID VARCHAR(10) NOT NULL,
	PRIMARY KEY(ACCOUNT_NUMBER), 
	FOREIGN KEY (CUS_ID) REFERENCES INDI_CUSTOMER(CUS_ID) 
	ON DELETE CASCADE,
	FOREIGN KEY (TYPE_ID) REFERENCES SAVING_ACCOUNT_TYPE(TYPE_ID) 
	ON DELETE CASCADE
);
CREATE TABLE WITHDRAWAL(
	W_ID VARCHAR(10) NOT NULL,
	AMOUNT NUMERIC(15,3) NOT NULL ,
	TIME TIME NOT NULL,
	DATE DATE NOT NULL,
	ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
	BRANCH_ID VARCHAR(10) NOT NULL,
	PRIMARY KEY(W_ID),
	FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES SAVING_ACCOUNT(ACCOUNT_NUMBER) 
	ON DELETE CASCADE,
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
	ON DELETE CASCADE	
);
CREATE TABLE FD(
	FD_ID VARCHAR(10) NOT NULL,
	AMOUNT NUMERIC(15,3) NOT NULL,
	ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
	FD_PLAN_ID VARCHAR(3),
          FOREIGN KEY (   FD_PLAN_ID   ) REFERENCES FD_Plan   (  FD_PLAN_ID   ),
  	FOREIGN KEY (   ACCOUNT_NUMBER   ) REFERENCES SAVING_ACCOUNT   (   ACCOUNT_NUMBER   ),
  	FOREIGN KEY (   ACCOUNT_NUMBER   ) REFERENCES CHECKING_ACCOUNT  (   ACCOUNT_NUMBER   )
);

 CREATE TABLE DEPOSIT(
	D_ID VARCHAR(10) NOT NULL,
	AMOUNT NUMERIC(15,3) NOT NULL,
	TIME TIME NOT NULL,
	DATE DATE NOT NULL,
	ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
	BRANCH_ID VARCHAR(10) NOT NULL,
	PRIMARY KEY(D_ID),
	FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES SAVING_ACCOUNT(ACCOUNT_NUMBER) 
	ON DELETE CASCADE,
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
	ON DELETE CASCADE

	);
CREATE TABLE ONLINE_LOAN(
	LOAN_ID VARCHAR(6),
	AMOUNT NUMERIC(15,3) NOT NULL,
	DATE DATE NOT NULL,
	INSTALMENT_VALUE NUMERIC(6,3) NOT NULL,
	STATUS VARCHAR(8) CHECK(STATUS IN ("PAID","NOT YET")) ,
	TYPE_ID VARCHAR(3) NOT NULL,
	FD_ID VARCHAR(10) NOT NULL,
	PRIMARY KEY(LOAN_ID),
	FOREIGN KEY (FD_ID ) REFERENCES FD(FD_ID) 
	ON DELETE CASCADE
);

CREATE TABLE CHECKING_ACCOUNT(
	ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
	BALANCE NUMERIC(15,3) CHECK (BALANCE>5000),
	USER_NAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(16) NOT NULL,
	EMAIL_ADDRESS VARCHAR(20) NOT NULL,
	CONTACT_NUMBER VARCHAR(10),
	CUS_ID VARCHAR(10) NOT NULL,
	BRANCH_ID VARCHAR(10) NOT NULL,
	PRIMARY KEY(ACCOUNT_NUMBER),
	FOREIGN KEY (CUS_ID) REFERENCES INDI_CUSTOMER(CUS_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
	ON DELETE CASCADE
);
CREATE TABLE MANUAL_LOAN(
	LOAN_ID VARCHAR(10) NOT NULL,
	AMOUNT NUMERIC(15,3) NOT NULL,
	DATE DATE NOT NULL,
	INSTALMENT_VALUE NUMERIC (15,3) NOT NULL,
	STATUS VARCHAR(8) CHECK(STATUS IN ("PAID","NOT YET")) ,
	TYPE_ID VARCHAR(10) NOT NULL,
	MANAGER_ID VARCHAR(10) NOT NULL,
	PRIMARY KEY(LOAN_ID),
	FOREIGN KEY (TYPE_ID) REFERENCES LOAN_TYPE(TYPE_ID)
	ON DELETE CASCADE,
	FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
	ON DELETE CASCADE

);